/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "db": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "hifis-service": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "redis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
